---
title: "daily_report_luna"
author: "Luna Yu"
date: "2025-03-10"
output: html_document
---

## March 10, 2025

1.  Created current_weather_functions.R (commit: 8efd613c376f6dbed9e528b5581f42108cfa6f59)
2.  Implemented:
    -   get_current_temperature() (commit: 1f4d67bef7db2c80ec0e5dac248b42091acf5ad5)
    -   get_current_wind() (commit: c02f2e98d11dcf7077ea38124180909a980e6c02)
    -   get_current_precipitation() (commit: cfa9f594bd206de23307d36ad8eaba9ae3514069)

## March 11, 2025

1.  Created test-current-weather.R for unit testing (commit: 35c789c6972de9d6a410bafed7d06f823e132cef)

## March 13, 2025

1.  Renamed and improved current weather functions: (commit: 220bdeecebc47295c36405f8255a586ae87e0a98)
    -   Updated API key handling
    -   Replaced source() with sys.source()
    -   Improved location validation
    -   Standardized function structure

## March 14, 2025

1.  Added unit tests for:
    -   get_current_temperature() (commit: e68f2027c7ec6a3c7ea45cd306ed6705022646ba)
    -   get_current_wind() (commit: 63602fd85bde0dd97da3afe34df653b254fc3245)
2.  Debugged API response handling & improved error handling in process_api_response() (commit: b131f7d41b2751693fe824ba8068cd9da61eb5b0)

## March 15, 2025

1.  Updated vignette section: Fetch Current Weather (commit: 7f475a8a877483c42eeffded693459a59c40685c)

## March 16, 2025

1.  Updated README:
    -   Added introduction, function list, and examples (commit: df5e684b6a2051744dc7d9c348160e3cbb0cc57f)