---
title: "DATA534 Daily Report"
author: "Yuzhu Han"
date: "2025-03-11"
output: html_document
---

# Date: March 10, 2025

### Work Summary
- Implemented the **`weather_alert_city()`** and **`weather_alert_lat`** functions
- Added **error handling** for API failures
- Ensured location data is included even when no alerts exist
- Debugged API URL formatting

### Function & Decision
- Used `httr` instead of `httrs` package for code consistency
- Handle the optional **state** and **country** parameters based on the examples in the API documentation. 
  - Need to check the API examples for optional parameters in other functions

### Contribution
- Work on the **alerts** endpoint of WeatherBit API
  - Finish two test functions out of four planned functions

### GitHub Commits
- https://github.com/TenTen-Teng/WeatherBitWrapper/commit/6c31d038b75113696dbb87183ace330a9c9e135f



# Date: March 11, 2025

### Work Summary
- Implemented the **`weather_alert_postal()`** and **`weather_alert_id()`** functions.
- Applied the self-built functions from **Teng**.

### Contribution
- Work on the **alerts** endpoint of WeatherBit API
  - Finish all four test functions

### GitHub Commits
- https://github.com/TenTen-Teng/WeatherBitWrapper/commit/dc2d5369a5994f6e99f9787593860297291d922b



# Date: March 13, 2025

### Work Summary
- Transfer the code to the new github repository `WeatherBitRWrapper`



# Date: March 14, 2025

### Work Summary
- Implement unit test script for alerts in `test_alerts.r`

### GitHub Commits 
- https://github.com/TenTen-Teng/WeatherBitRWrapper/commit/cbf72c03cfc4c61c723d7c84df47f5f2ae2be8f7



# Date: March 15, 2025

### Work Summary
- Debug unit test for alerts in `test_alerts.r`
- Update Vignette documentation for alerts

### GitHub Commits
- https://github.com/TenTen-Teng/WeatherBitRWrapper/commit/96b12884387afc2caef9f89a6aaed16df1f41158
- https://github.com/TenTen-Teng/WeatherBitRWrapper/commit/037e98794fdddb7c0588e12a420239e6e5fb592d



# Date: March 16, 2025

### Work Summary
- Update documentation in alerts.r for creating R help document
- Create package workflow chart 

### GitHub Commits
- https://github.com/TenTen-Teng/WeatherBitRWrapper/commit/afe5799b34e69816af7ea0e28adabf1da0ddef24
- https://github.com/TenTen-Teng/WeatherBitRWrapper/commit/94bf596d370759dfa3634d44d9f76f8fe0e5bf00
- https://github.com/TenTen-Teng/WeatherBitRWrapper/commit/d67d47a42262171fed9cab80c715530e6ae322d0


